trigger:
  -main
pool:
  name: 'Default'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

    
 -script: terraform init
  displayName: 'Terraform Init'
  env:
    ARM_CLIENT_ID: $(clientId)
    ARM_CLIENT_SECRET: $(clientId)
    ARM_SUBSCRIPTION_ID: $(clientId)
    ARM_TENANT_ID: $(clientId)


